// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbPG_N-iU15OQVybYtqPxy5mK7cBaUxBU',
    appId: '1:1006967606:web:a2c6f2033dd523d0557197',
    messagingSenderId: '1006967606',
    projectId: 'remindra-bc8e5',
    authDomain: 'remindra-bc8e5.firebaseapp.com',
    storageBucket: 'remindra-bc8e5.firebasestorage.app',
    measurementId: 'G-DBYS265X0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_peBAUXI6NrOc-KQES018ZZOosBBdmpM',
    appId: '1:1006967606:android:563211fb9e87cd6d557197',
    messagingSenderId: '1006967606',
    projectId: 'remindra-bc8e5',
    storageBucket: 'remindra-bc8e5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXwoy-RDudEAQeJCF-kRhv7uHVyly-p4',
    appId: '1:1006967606:ios:9859c61bb5548458557197',
    messagingSenderId: '1006967606',
    projectId: 'remindra-bc8e5',
    storageBucket: 'remindra-bc8e5.firebasestorage.app',
    iosBundleId: 'com.example.birthday_reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLXwoy-RDudEAQeJCF-kRhv7uHVyly-p4',
    appId: '1:1006967606:ios:9859c61bb5548458557197',
    messagingSenderId: '1006967606',
    projectId: 'remindra-bc8e5',
    storageBucket: 'remindra-bc8e5.firebasestorage.app',
    iosBundleId: 'com.example.birthday_reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbPG_N-iU15OQVybYtqPxy5mK7cBaUxBU',
    appId: '1:1006967606:web:5f624ab4fb0558de557197',
    messagingSenderId: '1006967606',
    projectId: 'remindra-bc8e5',
    authDomain: 'remindra-bc8e5.firebaseapp.com',
    storageBucket: 'remindra-bc8e5.firebasestorage.app',
    measurementId: 'G-6EYTWTCW55',
  );

}
